import type { Metadata } from 'next';
import './globals.css';
import Providers from './providers';
import { Open_Sans, Orbitron} from 'next/font/google';
import Head from 'next/head';
import Navigation from './componenets/navbar';
const Orbi = Orbitron({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={Orbi.className}>
        <Head>
          <link rel="icon" href="/favicon.ico" sizes="any" />
        </Head>
        <Providers>
          <Navigation />

          <main style={{ paddingTop: '7rem' }}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
